language: cpp
compiler:
  - gcc
  - clang

before_install:
    - git clone https://github.com/cpputest/cpputest ../cpputest
    - pushd ../cpputest
    - ./configure
    - make
    - sudo make install
    - popd

before_script:
    - ./make.sh debug

script: ./run-tests
