depends:
    - test-runner

source:
    - xmalloc.c
    - panic.c

target.arm:
    - ucos-iii/mutex.c

tests:
    - mock/semaphores.c
    - mock/mutex.c
    - mock/criticalsection.c
    - tests/semaphore_mock_test.cpp
    - tests/mutex_mock_test.cpp
    - tests/criticalsection_mock_test.cpp
    - tests/panic_mock_test.cpp
    - tests/malloc_test.cpp
    - tests/threading_test.cpp
    - threading_linux.c
